# -*- coding: utf-8 -*-
"""generate_synthetic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7-cZwBxwGZ-A1mpMpjUqC0XHnFw__7k
"""

import pandas as pd
import numpy as np

np.random.seed(42)
n = 1000
data = {
    'timestamp': range(n),
    'bid1': 100 + np.random.normal(0, 0.5, n).cumsum(),
    'ask1': 100.5 + np.random.normal(0, 0.5, n).cumsum(),
    'bid_vol1': np.random.randint(5, 20, n),
    'ask_vol1': np.random.randint(5, 20, n),
}
df = pd.DataFrame(data)
df['mid_price'] = (df['bid1'] + df['ask1']) / 2
df['target'] = (df['mid_price'].shift(-1) > df['mid_price']).astype(int)
df.to_csv('data/synthetic_lob.csv', index=False)
print("Generated: data/synthetic_lob.csv")